#pragma once
#include <structure/list/single_linked_type.h>
#include <structure/mman/mman.h>

synapse_structure_single_linked
synapse_structure_single_linked_initialize(synapse_structure_mman);

synapse_structure_single_linked
synapse_structure_single_linked_initialize_default();

void
synapse_structure_single_linked_destroy(synapse_structure_single_linked);