#pragma once
#include <structure/queue/linear/linear_queue_type.h>

void*
synapse_structure_linear_queue_node_data(synapse_structure_linear_queue_node);

size_t
synapse_structure_linear_queue_node_size(synapse_structure_linear_queue_node);