#pragma once
#include <structure/queue/priority/priority_queue_type.h>

synapse_structure_priority_queue_node
synapse_structure_priority_queue_push_front
	(synapse_structure_priority_queue, void*, size_t);

synapse_structure_priority_queue_node
synapse_structure_priority_queue_push_front_existing
	(synapse_structure_priority_queue, synapse_structure_priority_queue_node);

synapse_structure_priority_queue_node
synapse_structure_priority_queue_push_back
	(synapse_structure_priority_queue, void*, size_t);

synapse_structure_priority_queue_node
synapse_structure_priority_queue_push_back_existing
	(synapse_structure_priority_queue, synapse_structure_priority_queue_node);